# Generated by Django 4.2.20 on 2025-05-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout_users', '0005_alter_user_profile_picture'),
        ('scout_bookings', '0004_remove_servicebooking_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='service_provider',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='scout_users.serviceprovider'),
            preserve_default=False,
        ),
    ]
