# Generated by Django 4.2.20 on 2025-05-15 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scout_bookings', '0005_servicebooking_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='service_booking_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
